<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Prashant" failures="8" tests="10" name="TestLinux" time="122.014" errors="0" timestamp="2025-06-09T22:55:39 EDT">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="RegistrationTest" time="3.216"/>
  <testcase classname="testCases.TC002_AccountLoginTest" name="TestLogin" time="11.136">
    <failure type="java.lang.AssertionError" message="Login Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Failed expected [true] but found [false]
at testCases.TC002_AccountLoginTest.TestLogin(TC002_AccountLoginTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestLogin -->
  <testcase classname="testCases.TC003_LoginDDT" name="loginDataDTesting" time="11.061">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.loginDataDTesting(TC003_LoginDDT.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDTesting -->
  <testcase classname="testCases.TC003_LoginDDT" name="loginDataDTesting" time="10.271">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDDT.loginDataDTesting(TC003_LoginDDT.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDTesting -->
  <testcase classname="testCases.TC003_LoginDDT" name="loginDataDTesting" time="10.26">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDDT.loginDataDTesting(TC003_LoginDDT.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDTesting -->
  <testcase classname="testCases.TC003_LoginDDT" name="loginDataDTesting" time="10.271">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDDT.loginDataDTesting(TC003_LoginDDT.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDTesting -->
  <testcase classname="testCases.TC003_LoginDDT" name="loginDataDTesting" time="10.254">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDDT.loginDataDTesting(TC003_LoginDDT.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDTesting -->
  <testcase classname="testCases.TC003_LoginDDT" name="loginDataDTesting" time="10.264">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDDT.loginDataDTesting(TC003_LoginDDT.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDTesting -->
  <testcase classname="testCases.TC003_LoginDDT" name="loginDataDTesting" time="10.254">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDDT.loginDataDTesting(TC003_LoginDDT.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginDataDTesting -->
  <testcase classname="testCases.TC0004_CartAndCheckOutTest" name="CartAndCheckOutTest" time="2.919"/>
</testsuite> <!-- TestLinux -->
